version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: b2b-marketplace-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: b2b-marketplace
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: b2b-marketplace-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/b2b-marketplace
      - NODE_ENV=production
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
